### ISSUE TITLE
Amani-Zen(mobile): Map filter options covers the map itself 

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1053] opened 2015-12-09 21:18 UTC
On Dev, map filter options now cover the map instead of being an option at the top of the map.

Dev site: http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan
![mapfilter_dev](https://cloud.githubusercontent.com/assets/15751109/11699088/40774f6a-9e77-11e5-8f6c-3a29fecec22b.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296951
![mapfilter_invision1](https://cloud.githubusercontent.com/assets/15751109/11699093/4986d652-9e77-11e5-8b2d-e06a49e1c492.png)
![mapfilter_invision2](https://cloud.githubusercontent.com/assets/15751109/11699096/4ae4c374-9e77-11e5-91ce-8fb3c2143710.png)

**Comment by dannyzoujx** [comment] 2015-12-09 21:32
Also Invision design shows 2 columns of filter options instead of the stacked 1 column of filter options currently in dev site

**Comment by PeaceGeeks** [comment] 2015-12-10 02:10
Renee & @HwaHueySoh to discuss with Laura.

**Comment by PeaceGeeks** [comment] 2015-12-10 02:41
@zerhide - what do you think?

**Comment by zerhide** [comment] 2015-12-10 03:11
I think going with the show/hide option on the mockups is the best option... with the addition of changing "Filter By" to "Show Filters" and "Hide Filters"
<img width="444" alt="map-filter-closed" src="https://cloud.githubusercontent.com/assets/16233974/11705857/6cda84f6-9ea8-11e5-9113-1531eb50f0b3.png">
<img width="359" alt="map-filter-open" src="https://cloud.githubusercontent.com/assets/16233974/11705858/6ce532a2-9ea8-11e5-9168-475cdc92e6b6.png">

**Comment by arvandtiv** [comment] 2016-01-29 19:20
Please see dev for changes 
http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan

**Comment by PeaceGeeksProjects** [comment] 2016-01-29 20:01
Verified on iPhone.  @arvandtiv Please change the wording of the Show/Hide according to the mockups 
https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296951
https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296952

**Comment by arvandtiv** [comment] 2016-01-29 22:43
I think I got it this time please re visit the link !

**Comment by PeaceGeeksProjects** [comment] 2016-01-29 22:51
Better but not exactly as the mockups...
Can't you create the different flip flop text (Show Hide)
Also can't you use a widget (e.g. the one used on the team page) rather than show it on the menu bar?

Also, Please do not put in QA.  When done just move to Done :)

**Comment by arvandtiv** [comment] 2016-02-01 19:05
Please see dev for changes 
http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan

**Comment by MagdiRizkallah** [comment] 2016-02-02 00:48
Any chance the text can be flip flopped as per the Show/Hide design according to the mockups 
https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296951
https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296952

**Comment by PeaceGeeksProjects** [comment] 2016-03-18 21:06
Also on the phone, the + - button (to zoom on the map) appears on top of the filter when you expand it causing inability to select the top 2 items...

**Comment by MagdiRizkallah** [comment] 2016-05-06 22:35
Works fine on mobile but not on desktop.

**Comment by PeaceGeeksProjects** [comment] 2016-05-11 12:55
@bensinjin why did you move to Done.  It works well on mobile but on desktop, the filter is on top pf the right part of the Map...

**Comment by bensinjin** [comment] 2016-05-11 21:49
@limage could you see how the mobile version was implemented and extend it to other screen widths? I would reference the commit from @arvandtiv : https://github.com/PeaceGeeksSociety/amani/commit/dc39898399ca41f64deb98e6f03925d27677e5a1

**Comment by bensinjin** [comment] 2016-05-12 18:00
@PeaceGeeksProjects We've implemented a solution, moving to done please review, you will now see a "Show/Hide Filters" button above the map in both desktop & mobile.

**Comment by brandonq-appnovation** [comment] 2016-05-12 21:09
Tested this on multiple browsers and mobile devices. It mostly works: the filter appears above the map, and says "Show Filter" when it is closed, and "Hide Filter" when it is opened. Upon opening the filter, the filter functions as expected.

I discovered a few issues along the way. Most of them are just front-end theming, and do not impact functionality. However, I discovered a more major one that could be another issue altogether.

**Major Issue:**
- In browser widths between 480px and 768px (including mobile), the map does not display at all. This means that the map does not display at all in, for example, landscape mode for LG Nexus 4 and iPhone 5, and portrait mode for iPad 2. See below for an iPad 2 screenshot:
![image1 9](https://cloud.githubusercontent.com/assets/19274675/15230377/2b8bf3d8-184a-11e6-9e9e-27cfbd3c3e8a.PNG)

**Please let me know if another ticket needs to be raised for this issue.**

**Minor Issues:**
- The "None" box covers up the "Committed by" heading. This happens in all browsers and devices tested. This does not affect functionality at all, but may be confusing to users who do not know that the filters below are for "Committed by":
![pgks_map_none_covers_heading](https://cloud.githubusercontent.com/assets/19274675/15230427/6c2315de-184a-11e6-9e1c-b0adec3ebdfb.png)

- On mobile phone devices, the map controls cover up the checkboxes of the first few options in the filters. This does not affect functionality; the user can simply tap the words. See example screenshot below from LG Nexus 4:
![pgks_android_map_controls_cover_checkboxes](https://cloud.githubusercontent.com/assets/19274675/15230467/a7591f22-184a-11e6-9396-5147131b633c.png)

- On iOS devices (iPhone and iPad), the Full Screen button in the map controls (the one under + / -) does not display at all. If this is intended behaviour, then you may disregard this. See below screenshot from iPhone 5:
![image1 10](https://cloud.githubusercontent.com/assets/19274675/15230518/001662a0-184b-11e6-8644-853b305ea438.PNG)

**Comment by PeaceGeeksProjects** [comment] 2016-05-12 21:31
Verified on Dev

**Closed by PeaceGeeksProjects** 2016-05-12 21:31 UTC
Labels: Amani Zen Theme, BE Dev
