### ISSUE TITLE
Resources view needs to correspond to the mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1001] opened 2015-11-17 19:19 UTC
Need to add 'Featured' resources
Also need to add additional fields to general 'resouces'

**Comment by PeaceGeeks** [comment] 2016-01-08 17:02
Resources theming got broken recently - see http://dev.amani-zen-theme.peacegeeks.org/resources or screenshot

<img width="1280" alt="screen shot 2016-01-08 at 9 02 24 am" src="https://cloud.githubusercontent.com/assets/2263033/12204003/943d0384-b5e6-11e5-8607-cb1d6ec48579.png">

**Comment by limage** [comment] 2016-01-13 23:17
fixed! missing download button, that will be in separate ticket
https://github.com/PeaceGeeksSociety/amani/pull/1070

**Comment by akochlan** [comment] 2016-01-16 00:33
Validated on dev. Resource view doesn't match mockups:

- missed label 'Filter'
- wrong order of buttons Apply and Reset.
- missed switch for layout beside FEATURED RESOURCES
- missed Download button.

**Comment by PeaceGeeksProjects** [comment] 2016-01-19 03:18
duplicate of several detailed issues e.g. #1028

**Closed by PeaceGeeksProjects** 2016-01-19 03:18 UTC
Labels: Amani Zen Theme, BE Dev
