### ISSUE TITLE
AmaniZen-Donate button for Desktop & Mobile

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#896] opened 2015-09-29 18:50 UTC
Donate Button should be Themed and the same color as the menu banner

**Comment by arvandtiv** [comment] 2016-01-29 19:39
please review changes  http://dev.amani-zen-theme.peacegeeks.org/#

**Comment by PeaceGeeksProjects** [comment] 2016-01-29 20:04
duplicate of #1045

**Closed by PeaceGeeksProjects** 2016-01-29 20:04 UTC
Labels: Amani Zen Theme, Ready 4 Theming
