### ISSUE TITLE
Consider HybridAuth for Amani

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#15] opened 2013-05-03 18:53 UTC

**Comment by nbosco** [comment] 2015-08-11 17:03
Module installed and set up via amani-config menu. However, module wont print the ajax buttons on the user page. might be something to do with the tpl file.

**Comment by MagdiRizkallah** [comment] 2015-08-12 18:18
Please add comments on 'How To' create the corresponding App in each of the Social Media Sites or links to the Social Media wiki or page that explains it..

**Comment by nbosco** [comment] 2015-08-12 22:39
Added comments 'How To', and since creating apps for each individual social network would be cumbersome for each organization, you’re clients would require a lot more technical knowledge. To avoid making your clients do this, a solution would be to create an app for each social network under Peacegeeks’s handles & saving the access tokens permanently in the the module. I'll have to consult with another dev to see if this is the best option.

**Comment by MagdiRizkallah** [comment] 2015-08-13 04:49
I think we should add the ability to remove that function by the Amani Admin.

**Comment by PeaceGeeks** [comment] 2015-08-13 06:38
@MagdiRizkallah - can we discuss tomorrow?

**Comment by akochlan** [comment] 2016-01-07 16:51
Validated on dev: http://dev.amani-zen-theme.peacegeeks.org/

Steps to reproduce:

1. Logged in as Amani Admin
2. Select 'Configure Amani'
3. Select 'Manage Third-Party Logins'


Actual: * Module installed and set up via amani-config menu - Passed
            * 'How To' create the corresponding App in each of the Social Media Sites or links to the Social Media wiki ( Facebook, Twitter, Google, Yahoo )  - Passed.
            * add the ability to remove that function by the Amani Admin.  -  F
![hybridauth](https://cloud.githubusercontent.com/assets/16566072/12176316/fab93a4a-b534-11e5-86ad-0534287cded2.png)
ailed

**Comment by PeaceGeeksProjects** [comment] 2016-01-07 18:03
No real need for ability to remove that function by the Amani Admin.
Closing the issue

**Closed by PeaceGeeksProjects** 2016-01-07 18:03 UTC
