### ISSUE TITLE
From Amani Config menu, replace link for Logo & 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1166] opened 2016-04-09 02:50 UTC
Go to http://dev.amani-zen-theme.peacegeeks.org/admin/configure-amani (Configure Amani)
Select 'Manage Logo and Tagline' button
Replace link for button with link to admin/configure-amani/site-info 

Or else reconfigure the existing link so that the user can actually manage the logo and tagline

**Comment by MagdiRizkallah** [comment] 2016-04-09 03:00
@peacegeeks i think the existing link config/system/site-information is needed too.  It seems that the division you requested in #798 & #799 has not happenned and need to be implemented fully.

**Comment by MagdiRizkallah** [comment] 2016-05-06 22:41
Duplicate of  #798 & #799... Closing

**Closed by MagdiRizkallah** 2016-05-06 22:41 UTC
Labels: Amani Zen Theme, BE Dev
